### ISSUE TITLE
Travis CI failing to deploy to Heroku

### ISSUE THREAD

**Issue by ajtran303** [Kathybui732/viewing_party#33]
Our production environment hasn't updated in the last three pull requests

The build logs show the same messages:

```
Preparing deploy
No stash entries found.
API request failed.
Message: Couldn't find that app.
Reference: 
failed to deploy
```

### Edit: this may not be the strat, see followup posts below

I think we can fix it with some command line prompts:
1. manually deploy main branch
2. set the ENV vars
```
git branch main
git push origin heroku
figaro heroku:set -e production
```

**Comment by ajtran303** [comment]
But I actually don't know how to debug the [Travis build log](https://travis-ci.org/github/Kathybui732/viewing_party/builds/719495206) so I may be off the mark.

**Comment by ajtran303** [comment]
> Builds triggered from Pull Requests will never trigger a deploy.

https://docs.travis-ci.com/user/deployment/heroku/

**Comment by ajtran303** [comment]
```
# .travis.yml

langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: RJhFd/bVJnfOmlNQPESFgU4nh6o5ELXsa5WHLE9gQEoSdWKcS1akCcsaW0Zc+jCMqWoXSe+2DMQQ5XkCeZ4NK6t29US+cLcXKFtt+QnB/hrNKyv/h3DbAvKdqsxXJko8JYeeseRcc+gtTOx8OF2FV4XJOk/j1qVxwSsay4PE/KAops1OziGXSnex4K+71KKvtpOx5Mo1dqfxs49gxBQUsymAAvo1B6OpVJtAID7dnOyyqNUKlbXoSrNb1O+3vl2nUoFD+Q67nmMi33iRCKOsAv0XjeGRsmkVqZDuHs1afvS6mWHGGfCvVFtXkT/YWZGPQm5y0Oc9x1pv1+J+MZT9O0fAlokkZfhld1qX6XB4UF+KE/0kjnINiAtQdXUA7tFlzCTK9u06AAZIyPFavSmgS5hPozAnEv/zYDKHbGolSL9+npcyj86VO6vI68N+/Dljx4BrMg9tA9sINszr5dTJHZ2AXAH6VGbonDyCLk6DBrNcrjzVbdPCp8o209xc0bG9q2Ewa7VVHiZQaK1ueatspL6iOAohZ9hVoZF0OyAmnaHLIYOpGLhVMvcPNahAL1Wen7f1+jxcUTGJfGv1wjEpTHPbXccrhjzB2BSllQ7s4ZTRUpPGmFB683rj2tq5asFRJicgfrtKaldnLLrqr0s3T1MSvglsjrTa725YfpVvNRg=
  app: 
  run: rails db:migrate
  on:
    repo: Kathybui732/viewing_party
    branch: main
```

`app:` key is not paired with a value. That would totally explain `Message: Couldn't find that app.`

This [StackOverflow post](https://stackoverflow.com/questions/52251241/api-request-fails-on-travis-ci) says that we should use the randomly-generated app name with dashes for the key-value pair.
